server:
  port : 8080
  servlet:
    context-path: /
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/msGraph
    username: root
    password: Phx11LOML!
  sql:
    init:
      platform: mariadb